### ISSUE TITLE
Question on Preintegration

### ISSUE THREAD

**Issue by joshi-bharat** [uzh-rpg/rpg_svo_pro_gps#2]
Hi,

The preintegration terms (for IMU error as well) do not exactly match the paper "On-Manifold Preintegration for Real-Time Visual–Inertial Odometry". 

The OKVIS paper does not have a detailed analysis of that. So, I was curious if you have access to any resource that matches the implementation here.

Or am I missing something here regarding the implementation?

Thanks,

**Comment by gcioffi** [comment]
Hi, 

Unfortunately, I do not have a derivation that exactly matches the implementation. 

This https://arxiv.org/pdf/1912.11986.pdf might be of help.
